# Generated by Django 4.2 on 2023-05-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoGame',
            fields=[
                ('video_game_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=512)),
                ('genre', models.CharField(max_length=512)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('image_url', models.ImageField(default='imgs/videogames/Old_Harbour.png', upload_to='templates/videogame_imgs')),
            ],
        ),
    ]
