# Generated by Django 4.2 on 2023-06-01 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0003_order_delete_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usershippingdetails',
            old_name='address_line1',
            new_name='address_line',
        ),
        migrations.RemoveField(
            model_name='usershippingdetails',
            name='address_line2',
        ),
        migrations.RemoveField(
            model_name='usershippingdetails',
            name='bank_details',
        ),
    ]
