# Generated by Django 4.2 on 2023-06-05 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0005_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='card',
            name='cvc',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='card',
            name='exp_month',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='card',
            name='exp_year',
            field=models.IntegerField(),
        ),
    ]
