# Generated by Django 4.2 on 2023-06-05 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shipping', '0006_alter_card_card_number_alter_card_cvc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('total_amount', models.IntegerField()),
                ('receipt_id', models.AutoField(primary_key=True, serialize=False)),
                ('items', models.TextField()),
                ('tax', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
