# Generated by Django 4.2 on 2023-06-07 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0007_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='usershippingdetails',
            name='shipping_speed',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
