# Generated by Django 4.2 on 2023-06-08 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0015_remove_usershippingdetails_shipping_speed'),
    ]

    operations = [
        migrations.AddField(
            model_name='usershippingdetails',
            name='speed',
            field=models.CharField(default='standard', max_length=100),
        ),
    ]
