# Generated by Django 4.2 on 2023-06-08 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0017_receipt_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='delivery_option',
            field=models.CharField(default='standard', max_length=100),
            preserve_default=False,
        ),
    ]
